import { expect, test } from '@playwright/test'

test('preview actions share example state across desktop and mobile panels', async ({ page }) => {
    await page.goto('/components/contentstate')
    const preview = page.locator('.documentation-preview').filter({ has: page.locator('.async-example') })
    const actions = preview.getByRole('complementary', { name: 'Preview actions' })
    await expect(actions.getByRole('button', { name: 'Load users', exact: true })).toBeVisible()
    const panelBox = await actions.boundingBox()
    const frameBox = await preview.locator('.documentation-preview__frame').boundingBox()
    expect(panelBox!.width / frameBox!.width).toBeCloseTo(0.2, 1)
    await actions.getByRole('button', { name: 'Load users', exact: true }).click()
    await expect(preview.getByText('Ada Lovelace', { exact: true })).toBeVisible()

    await preview.getByRole('radio', { name: 'Mobile', exact: true }).click()
    await expect(actions).toHaveCount(0)
    await preview.getByRole('button', { name: 'Actions', exact: true }).filter({ visible: true }).click()
    await expect(page.getByRole('dialog', { name: 'Preview actions' })).toBeVisible()
    await page.keyboard.press('Escape')
    await preview.getByRole('radio', { name: 'Desktop', exact: true }).click()
    await expect(actions).toBeVisible()

    await page.setViewportSize({ width: 390, height: 844 })
    const trigger = preview.getByRole('button', { name: 'Actions', exact: true }).filter({ visible: true })
    await expect(trigger).toBeVisible()
    await expect(actions).toHaveCount(0)
    await expect(preview.getByText('Ada Lovelace', { exact: true })).toBeVisible()
    await trigger.click()
    const dropdown = page.getByRole('dialog', { name: 'Preview actions' })
    await expect(dropdown).toBeVisible()
    await expect(dropdown).not.toHaveAttribute('aria-modal', 'true')
    await expect(page.locator('.h-overlay__backdrop')).toHaveCount(0)
    await expect(page.locator('html')).not.toHaveClass(/h-overlay-lock-scroll/)
    const dropdownBox = await dropdown.boundingBox()
    expect(dropdownBox!.height).toBeLessThan(180)
    expect(dropdownBox!.width).toBeLessThan(300)
    await dropdown.getByRole('button', { name: 'Simulate error' }).click()
    await expect(dropdown).toBeHidden()
    await expect(preview.getByRole('status', { name: 'Loading users' })).toBeVisible()
    await expect(preview.getByText('Unable to load users', { exact: true })).toBeVisible()
    await trigger.click()
    await page.keyboard.press('Escape')
    await expect(dropdown).toBeHidden()
    await expect(trigger).toBeFocused()
    await expect(preview.getByText('Unable to load users', { exact: true })).toBeVisible()
    await trigger.click()
    await dropdown.getByRole('button', { name: 'Load users', exact: true }).click()
    await expect(dropdown).toBeHidden()
    await expect(preview.getByText('Ada Lovelace', { exact: true })).toBeVisible()
    await trigger.click()
    await preview.locator('.documentation-preview__content').click()
    await expect(dropdown).toBeHidden()
    await trigger.click()
    await page.setViewportSize({ width: 1280, height: 720 })
    await expect(dropdown).toHaveCount(0)
    await expect(actions.getByRole('button', { name: 'Load users', exact: true })).toBeVisible()
    await expect(page.locator('html')).not.toHaveClass(/h-overlay-lock-scroll/)
    await expect(preview.getByText('Ada Lovelace', { exact: true })).toBeVisible()

    const plainPreview = page.locator('.documentation-preview').first()
    await expect(plainPreview.locator('.documentation-preview__actions')).toHaveCount(0)
})

