import { expect, test } from '@playwright/test'
import AxeBuilder from '@axe-core/playwright'

test('custom actions, trigger ARIA, Escape, outside click and Tab', async ({ page }) => {
    await page.goto('/components/dropdown')
    const trigger = page.locator('.dropdown-basic-example').getByRole('button', { name: 'Actions', exact: true })
    await trigger.focus(); await page.keyboard.press('ArrowDown')
    const panel = page.getByRole('dialog', { name: 'File actions' })
    await expect(panel).toBeVisible()
    await expect(trigger).toHaveAttribute('aria-expanded', 'true')
    await expect(panel.getByRole('button', { name: 'New file' })).toBeFocused()
    const accessibility = await new AxeBuilder({ page }).include('[data-h0n-component="dropdown-content"]').analyze()
    expect(accessibility.violations).toEqual([])
    const triggerBox = await trigger.boundingBox()
    const panelBox = await panel.boundingBox()
    expect(panelBox!.width).toBeGreaterThanOrEqual(220)
    expect(Math.abs(panelBox!.x - triggerBox!.x)).toBeLessThan(2)
    await page.keyboard.press('Escape')
    await expect(panel).toHaveCount(0); await expect(trigger).toBeFocused()
    await trigger.click(); await panel.getByRole('button', { name: 'Copy link' }).click()
    await expect(panel).toHaveCount(0)
    await expect(page.locator('.dropdown-basic-example p')).toHaveText('Copy link')
    await expect(trigger).toBeFocused()
    await trigger.click(); await page.getByRole('heading', { name: 'Dropdown', exact: true }).click()
    await expect(panel).toHaveCount(0)
    await trigger.click(); await panel.getByRole('button', { name: 'Delete file' }).focus(); await page.keyboard.press('Tab')
    await expect(panel).toHaveCount(0)
    expect(await page.evaluate(() => document.activeElement?.getAttribute('aria-label'))).toBe('Copy code')
})

test('image trigger and arbitrary form content remain interactive', async ({ page }) => {
    await page.goto('/components/dropdown')
    const trigger = page.getByRole('button', { name: 'Edit Alex profile' })
    await trigger.focus(); await page.keyboard.press('Space')
    const panel = page.getByRole('dialog', { name: 'Edit profile', exact: true })
    await expect(panel.getByRole('textbox', { name: 'Display name' })).toBeFocused()
    await panel.getByRole('textbox').fill('Taylor')
    await expect(panel).toBeVisible()
    await panel.getByRole('button', { name: 'Save profile' }).click()
    await expect(panel).toHaveCount(0)
    await expect(page.locator('.dropdown-custom-example p')).toHaveText('Saved: Taylor')
    await expect(trigger).toBeFocused()
    await trigger.press('Enter'); await page.keyboard.press('Shift+Tab')
    await expect(panel).toHaveCount(0); await expect(trigger).toBeFocused()
})

test('nested modal/Select, height limits, scroll and dismissal ordering', async ({ page }) => {
    await page.goto('/components/dropdown')
    await page.getByRole('button', { name: 'Open workspace dialog' }).click()
    const modal = page.getByRole('dialog', { name: 'Workspace settings', exact: true })
    const trigger = modal.getByRole('button', { name: 'Folder settings', exact: true })
    await trigger.click()
    const dropdown = page.getByRole('dialog', { name: 'Folder settings', exact: true })
    await expect(dropdown).toBeVisible()
    const size = await dropdown.evaluate(el => ({ height: el.getBoundingClientRect().height, scroll: el.scrollHeight, z: +getComputedStyle(el).zIndex }))
    expect(size.height).toBeLessThanOrEqual(180)
    expect(size.scroll).toBeGreaterThan(size.height)
    expect(size.z).toBeGreaterThan(1000)
    await dropdown.getByRole('combobox', { name: 'Folder' }).click()
    await page.keyboard.press('Escape')
    await expect(page.getByRole('listbox')).toHaveCount(0)
    await expect(dropdown).toBeVisible()
    await expect(modal).toBeVisible()
    await dropdown.getByRole('combobox', { name: 'Folder' }).click()
    await page.getByRole('listbox').getByRole('option', { name: 'Work', exact: true }).click()
    await expect(dropdown).toBeVisible()
    await page.keyboard.press('Escape')
    await expect(dropdown).toHaveCount(0); await expect(modal).toBeVisible(); await expect(trigger).toBeFocused()
    await page.keyboard.press('Escape'); await expect(modal).toHaveCount(0)
    await expect(page.getByRole('button', { name: 'Unavailable actions' })).toBeDisabled()
})

for (const theme of ['light', 'dark'] as const) {
    for (const accent of ['default', 'telegram', 'uber'] as const) {
        test(`${theme}/${accent}: mobile viewport bounds and colors`, async ({ page }) => {
            await page.setViewportSize({ width: 360, height: 640 })
            await page.goto('/components/dropdown')
            await page.evaluate(({ theme, accent }) => { document.documentElement.dataset.h0nTheme = theme; document.documentElement.dataset.h0nAccent = accent }, { theme, accent })
            await page.locator('.dropdown-basic-example').getByRole('button', { name: 'Actions' }).click()
            const panel = page.getByRole('dialog', { name: 'File actions' })
            await expect(panel).toBeVisible()
            const box = await panel.boundingBox()
            expect(box!.x).toBeGreaterThanOrEqual(7)
            expect(box!.x + box!.width).toBeLessThanOrEqual(353)
            expect(box!.y).toBeGreaterThanOrEqual(7)
            expect(box!.y + box!.height).toBeLessThanOrEqual(633)
            expect(await panel.evaluate(el => getComputedStyle(el).backgroundColor)).not.toBe('rgba(0, 0, 0, 0)')
            if (accent === 'uber') await page.screenshot({ path: `test-results/dropdown-${theme}-mobile.png` })
        })
    }
}

test('RTL logical alignment and motion off', async ({ page }) => {
    await page.goto('/components/dropdown')
    await page.evaluate(() => { document.documentElement.dir = 'rtl'; document.documentElement.dataset.h0nAnimation = 'off' })
    const trigger = page.locator('.dropdown-basic-example').getByRole('button', { name: 'Actions' })
    await trigger.click()
    const panel = page.getByRole('dialog', { name: 'File actions' })
    await expect(panel).toBeVisible()
    const a = await trigger.boundingBox(); const b = await panel.boundingBox()
    expect(Math.abs(a!.x + a!.width - b!.x - b!.width)).toBeLessThan(2)
    expect(await panel.evaluate(el => getComputedStyle(el).transitionDuration)).toBe('0s')
    await page.keyboard.press('Escape'); await expect(panel).toHaveCount(0); await expect(trigger).toBeFocused()
})
