import type { ComponentAgentRecordV1 } from '../schema.ts'

export const alertDialogAgentRecord = {
    schemaVersion: 1,
    component: 'H0AlertDialog',
    status: 'migrated',
    summary: 'Blocking alert dialog for explicit confirmation or cancellation of a consequential action.',
    imports: { components: ['H0AlertDialog'], types: ['H0AlertDialogBackdrop', 'H0AlertDialogEmits', 'H0AlertDialogProps', 'H0AlertDialogTone'], styles: ['@h0nio/ui/style.css'] },
    api: {
        props: [
            { name: 'modelValue', type: 'boolean', default: 'undefined', description: 'Controlled open state used by v-model.' },
            { name: 'defaultValue', type: 'boolean', default: 'false', description: 'Initial open state when the component is uncontrolled.' },
            { name: 'tone', type: 'H0AlertDialogTone', default: "'info'", description: "Semantic treatment: 'info', 'success', 'warning', or 'danger'." },
            { name: 'backdrop', type: 'H0AlertDialogBackdrop', default: "'opaque'", description: "Backdrop appearance: 'opaque', 'blur', or 'transparent'; backdrop clicks never dismiss this critical dialog." },
            { name: 'title', type: 'string', default: "''", description: 'Visible title and preferred accessible dialog name.' },
            { name: 'text', type: 'string', default: "''", description: 'Fallback description rendered when the default slot is absent.' },
            { name: 'confirmText', type: 'string', default: "''", description: 'Confirmation label; falls back to locale text.' },
            { name: 'cancelText', type: 'string', default: "''", description: 'Cancellation label; falls back to locale text.' },
            { name: 'closeOnEsc', type: 'boolean', default: 'true', description: 'Allows Escape to close the dialog.' },
            { name: 'ariaLabel', type: 'string', default: "''", description: 'Accessible name used when title is empty before the locale fallback.' },
            { name: 'closeAriaLabel', type: 'string', default: "''", description: 'Accessible label for the icon-only close button.' },
            { name: 'teleportTo', type: 'string | HTMLElement', default: "'body'", description: 'Teleport destination for the overlay root.' },
            { name: 'teleportDisabled', type: 'boolean', default: 'false', description: 'Renders the overlay in place instead of teleporting it.' },
            { name: 'initialFocus', type: 'string | HTMLElement', default: 'undefined', description: 'Selector or element to focus when opened.' },
            { name: 'returnFocus', type: 'boolean | HTMLElement', default: 'true', description: 'Returns focus to the opener or a supplied element after closing.' },
            { name: 'lockScroll', type: 'boolean', default: 'true', description: 'Locks document scrolling while open.' },
        ],
        events: [
            { name: 'update:modelValue', type: 'boolean', description: 'Requests a controlled open-state update.' },
            { name: 'change', type: 'boolean', description: 'Reports every committed open-state change.' },
            { name: 'confirm', type: '—', description: 'Reports confirmation before the dialog closes.' },
            { name: 'cancel', type: '—', description: 'Reports cancellation before the dialog closes.' },
            { name: 'close', type: '—', description: 'Reports any close path.' },
        ],
        slots: [
            { name: 'default', type: '—', description: 'Structured description replacing text.' },
            { name: 'title', type: '—', description: 'Structured visible title replacing title text.' },
            { name: 'actions', type: '{ cancel: () => void; confirm: () => void; close: () => void }', description: 'Replaces default actions and receives decision callbacks.' },
        ],
        exposed: [],
        types: [
            { name: 'H0AlertDialogTone', fields: [{ name: 'H0AlertDialogTone', type: "'danger' | 'info' | 'success' | 'warning'", description: 'Semantic intent used for the icon, accent, and default confirmation tone.' }] },
            { name: 'H0AlertDialogBackdrop', fields: [{ name: 'H0AlertDialogBackdrop', type: "'opaque' | 'blur' | 'transparent'", description: 'Available backdrop appearances; backdrop clicks never dismiss an alert dialog.' }] },
        ],
    },
    useWhen: ['A destructive or consequential action requires an explicit decision.', 'The user must acknowledge risk before a workflow continues.'],
    avoidWhen: ['Feedback is informational or non-blocking.', 'The workflow is a general form better suited to H0Modal.'],
    accessibility: ['Use a specific title.', 'Keep a clear cancellation path.', 'Choose initial focus conservatively for destructive actions.'],
    styling: ['Use semantic tone and public H0N tokens.', 'Treat internal alert-dialog selectors as implementation details.'],
    responsive: ['Keep copy and actions concise so they wrap on narrow screens.'],
    performance: ['Keep blocking content small; it mounts only while open.'],
    examples: [
        { key: 'components/alert-dialog/BasicExample', purpose: 'Controlled destructive confirmation and decision events.' },
        { key: 'components/alert-dialog/TonesExample', purpose: 'Information, success, warning, and danger decision contexts.' },
        { key: 'components/alert-dialog/CustomActionsExample', purpose: 'Slotted title, description, custom actions, and conservative initial focus.' },
        { key: 'components/alert-dialog/BackdropsExample', purpose: 'Opaque, blurred, and transparent backdrop treatments.' },
    ],
    relatedComponents: ['H0Alert', 'H0Button', 'H0Modal', 'H0Toast'],
} satisfies ComponentAgentRecordV1
