import type { ComponentAgentRecordV1 } from '../schema.ts'

export const buttonAgentRecord = {
    schemaVersion: 1,
    component: 'H0Button',
    status: 'migrated',
    summary: 'Base action control for forms, toolbars, dialogs, command surfaces, and link-like actions.',
    imports: {
        components: ['H0Button'],
        types: ['H0ButtonProps', 'H0ButtonSize', 'H0ButtonTone', 'H0ButtonTypeVariant', 'H0ButtonVariant', 'H0IconSource'],
        styles: ['@h0nio/ui/style.css'],
    },
    api: {
        props: [
            { name: 'tone', type: 'H0ButtonTone', default: "'default'", description: 'Semantic intent used by solid and soft appearances.' },
            { name: 'variant', type: 'H0ButtonVariant', default: "'solid'", description: 'Visual emphasis of the button.' },
            { name: 'size', type: 'H0ButtonSize', default: "'md'", description: 'Controls height, horizontal padding, font size, and icon-only dimensions.' },
            { name: 'buttonType', type: 'H0ButtonTypeVariant', default: "'default'", description: 'Selects text-only, icon-with-text, or icon-only content.' },
            { name: 'icon', type: 'H0IconSource', default: 'undefined', description: 'Legacy node definition or body definition imported from an individual @h0nio/icons subpath.' },
            { name: 'iconTitle', type: 'string', default: "''", description: 'Optional accessible SVG title. It does not replace ariaLabel on icon-only controls.' },
            { name: 'type', type: "'button' | 'submit' | 'reset'", default: "'button'", description: 'Native button type when the root is a button element.' },
            { name: 'disabled', type: 'boolean', default: 'false', description: 'Prevents pointer and keyboard activation.' },
            { name: 'loading', type: 'boolean', default: 'false', description: 'Disables interaction, displays a spinner, and sets aria-busy.' },
            { name: 'loadingText', type: 'string', default: 'undefined', description: 'Replaces slot content with a loading message.' },
            { name: 'fullWidth', type: 'boolean', default: 'false', description: 'Makes the control fill its container width.' },
            { name: 'rounded', type: 'boolean', default: 'true', description: 'Removes the radius when false. Icon-only buttons stay circular.' },
            { name: 'ariaLabel', type: 'string', default: "''", description: 'Accessible label. Required when no visible text identifies the action.' },
            { name: 'as', type: 'string | Component', default: "'button'", description: 'Element tag or Vue component used as the root.' },
            { name: 'href', type: 'string', default: 'undefined', description: 'Destination for anchor-style buttons.' },
            { name: 'to', type: 'unknown', default: 'undefined', description: 'Destination intended for compatible custom link components.' },
            { name: 'rootAttrs', type: 'Record<string, unknown>', default: 'undefined', description: 'Advanced root attributes merged after ordinary fallthrough attributes.' },
        ],
        events: [
            { name: 'click', type: 'MouseEvent', description: 'Native event from the rendered root. Suppressed while disabled or loading.' },
            { name: 'focus', type: 'FocusEvent', description: 'Native focus event from the rendered root.' },
            { name: 'blur', type: 'FocusEvent', description: 'Native blur event from the rendered root.' },
        ],
        slots: [
            { name: 'default', type: '—', description: 'Visible button label. Hidden for onlyIcon; retained beside the spinner while loading unless loadingText is provided.' },
            { name: 'icon', type: '—', description: 'Custom Vue component, SVG, or other icon content. Takes precedence over the icon prop.' },
        ],
        exposed: [],
        types: [
            { name: 'H0ButtonTone', fields: [{ name: 'H0ButtonTone', type: "'default' | 'primary' | 'success' | 'warning' | 'danger'", description: 'Supported semantic button tones.' }] },
            { name: 'H0ButtonVariant', fields: [{ name: 'H0ButtonVariant', type: "'solid' | 'soft' | 'outline' | 'ghost'", description: 'Supported visual emphasis variants.' }] },
            { name: 'H0ButtonSize', fields: [{ name: 'H0ButtonSize', type: "'sm' | 'md' | 'lg'", description: 'Supported button sizes. Alias of the shared H0Size type.' }] },
            { name: 'H0ButtonTypeVariant', fields: [{ name: 'H0ButtonTypeVariant', type: "'default' | 'withIcon' | 'onlyIcon'", description: 'Supported text and icon content layouts.' }] },
        ],
    },
    useWhen: ['Triggering an action in a form, toolbar, dialog, or command surface.', 'Rendering a visually button-like semantic link with as="a" and href.'],
    avoidWhen: ['Navigation should use a normal link when button styling is unnecessary.', 'A set of adjacent related actions should use H0ButtonGroup.', 'A selected state is required; use a selection control instead.'],
    accessibility: ['Use a concise, action-oriented visible label.', 'Provide ariaLabel for every icon-only button.', 'Keep type="button" unless the action intentionally submits or resets a form.', 'Do not communicate destructive or status meaning through color alone.'],
    styling: ['Prefer tone, variant, size, and public design tokens over internal selectors.', 'Treat .h-button and --h-button-* variables as implementation details.'],
    responsive: ['Use fullWidth for stacked mobile actions and narrow containers.', 'Keep labels short enough to avoid overflow at small widths.'],
    performance: ['Avoid recreating icon definitions and rootAttrs objects on every render when they can remain stable.'],
    examples: [
        { key: 'components/button/BasicExample', purpose: 'Basic primary action.' },
        { key: 'components/button/AppearanceExample', purpose: 'All supported tones and variants.' },
        { key: 'components/button/SizesExample', purpose: 'Small, medium, and large sizes.' },
        { key: 'components/button/WithIconExample', purpose: 'Visible labels paired with icons.' },
        { key: 'components/button/IconOnlyExample', purpose: 'Accessible icon-only actions.' },
        { key: 'components/button/StatesExample', purpose: 'Disabled and loading states.' },
        { key: 'components/button/FullWidthExample', purpose: 'Full-width layout.' },
        { key: 'components/button/LinksExample', purpose: 'Anchor rendering for navigation.' },
        { key: 'components/button/ClickExample', purpose: 'Native click event handling.' },
    ],
    relatedComponents: ['H0Icon', 'H0ButtonGroup', 'H0Segment'],
} satisfies ComponentAgentRecordV1
