import type { ComponentAgentRecordV1 } from '../schema.ts'

export const commandAgentRecord = {
    schemaVersion: 1,
    component: 'H0Command',
    status: 'migrated',
    summary: 'Modal command menu with a configurable trigger, hotkey opening, searchable grouped items, and keyboard selection.',
    imports: {
        components: ['H0Command'],
        types: ['H0CommandBackdrop', 'H0CommandEmits', 'H0CommandItem', 'H0CommandProps', 'H0CommandSize', 'H0CommandVariant', 'H0CommandWindowSize'],
        styles: ['@h0nio/ui/style.css'],
    },
    api: {
        props: [
            { name: 'modelValue', type: 'boolean', default: 'undefined', description: 'Controlled open state used by v-model.' },
            { name: 'defaultValue', type: 'boolean', default: 'false', description: 'Initial uncontrolled open state.' },
            { name: 'query', type: 'string', default: 'undefined', description: 'Controlled search query used by v-model:query.' },
            { name: 'defaultQuery', type: 'string', default: "''", description: 'Initial uncontrolled search query.' },
            { name: 'items', type: 'readonly H0CommandItem[]', default: '[]', description: 'Commands filtered and rendered in the list.' },
            { name: 'variant', type: 'H0CommandVariant', default: "'surface'", description: 'Built-in trigger appearance.' },
            { name: 'backdrop', type: 'H0CommandBackdrop', default: "'opaque'", description: 'Modal backdrop appearance.' },
            { name: 'size', type: 'H0CommandSize', default: "'md'", description: 'Built-in trigger size.' },
            { name: 'windowSize', type: 'H0CommandWindowSize', default: "'md'", description: 'Command window width and result-list height.' },
            { name: 'hotkey', type: 'string', default: "''", description: "Global key combination such as 'mod+k', 'ctrl+shift+p', or '/'." },
            { name: 'triggerLabel', type: 'string', default: "''", description: 'Built-in trigger text before locale fallback.' },
            { name: 'placeholder', type: 'string', default: "''", description: 'Search placeholder before locale fallback.' },
            { name: 'emptyText', type: 'string', default: "''", description: 'Empty-result text before locale fallback.' },
            { name: 'ariaLabel', type: 'string', default: "''", description: 'Command dialog accessible name before locale fallback.' },
            { name: 'disabled', type: 'boolean', default: 'false', description: 'Disables trigger and hotkey opening.' },
            { name: 'closeOnSelect', type: 'boolean', default: 'true', description: 'Closes the window after selecting an enabled command.' },
            { name: 'closeOnBackdrop', type: 'boolean', default: 'true', description: 'Allows backdrop dismissal.' },
            { name: 'closeOnEsc', type: 'boolean', default: 'true', description: 'Allows Escape dismissal.' },
            { name: 'resetQueryOnClose', type: 'boolean', default: 'true', description: 'Clears search text after the window closes.' },
            { name: 'showFooter', type: 'boolean', default: 'true', description: 'Shows built-in keyboard hints when no custom footer is supplied.' },
            { name: 'teleportTo', type: 'string | HTMLElement', default: "'body'", description: 'Overlay teleport destination.' },
            { name: 'teleportDisabled', type: 'boolean', default: 'false', description: 'Renders the overlay beside the trigger in the DOM.' },
            { name: 'returnFocus', type: 'boolean | HTMLElement', default: 'true', description: 'Controls focus restoration after closing.' },
            { name: 'lockScroll', type: 'boolean', default: 'true', description: 'Locks document scrolling while open.' },
            { name: 'rootAttrs', type: 'Record<string, unknown>', default: 'undefined', description: 'Attributes for the root wrapper.' },
            { name: 'triggerAttrs', type: 'Record<string, unknown>', default: 'undefined', description: 'Native and ARIA attributes for the built-in trigger.' },
        ],
        events: [
            { name: 'update:modelValue', type: 'boolean', description: 'Requests controlled open-state changes.' },
            { name: 'update:query', type: 'string', description: 'Requests controlled query changes.' },
            { name: 'change', type: 'boolean', description: 'Reports committed open-state changes.' },
            { name: 'open', type: '—', description: 'Reports the component opening.' },
            { name: 'close', type: '—', description: 'Reports any close path.' },
            { name: 'search', type: 'string', description: 'Reports user or exposed-API query changes.' },
            { name: 'select', type: 'H0CommandItem', description: 'Reports selection of an enabled command.' },
        ],
        slots: [
            { name: 'trigger', type: '{ open; close; toggle; isOpen; disabled }', description: 'Replaces the built-in trigger and receives state callbacks.' },
            { name: 'header', type: '{ query: string; close: () => void }', description: 'Content placed above the search field.' },
            { name: 'group-label', type: '{ group: string }', description: 'Custom group label.' },
            { name: 'item', type: '{ item: H0CommandItem; active: boolean; query: string }', description: 'Replaces the complete command item content.' },
            { name: 'item-start', type: '{ item: H0CommandItem; active: boolean }', description: 'Custom leading item visual.' },
            { name: 'item-end', type: '{ item: H0CommandItem; active: boolean }', description: 'Custom trailing item content.' },
            { name: 'empty', type: '{ query: string }', description: 'Empty search result.' },
            { name: 'footer', type: '{ activeItem?: H0CommandItem; close: () => void }', description: 'Replaces built-in keyboard hints.' },
        ],
        exposed: [
            { name: 'open', type: '() => void', description: 'Opens the command window when enabled.' },
            { name: 'close', type: '() => void', description: 'Closes the command window.' },
            { name: 'toggle', type: '() => void', description: 'Toggles the command window.' },
            { name: 'focus', type: '() => void', description: 'Focuses the built-in trigger.' },
            { name: 'setQuery', type: '(value: string) => void', description: 'Sets the query and emits search.' },
        ],
        types: [
            {
                name: 'H0CommandItem',
                fields: [
                    { name: 'value', type: 'string | number', description: 'Stable command value.' },
                    { name: 'label', type: 'string', description: 'Visible command label.' },
                    { name: 'description', type: 'string', description: 'Optional supporting copy.' },
                    { name: 'group', type: 'string', description: 'Optional group heading.' },
                    { name: 'keywords', type: 'readonly string[]', description: 'Additional searchable terms.' },
                    { name: 'icon', type: 'H0IconDefinition', description: 'Optional structural H0N icon.' },
                    { name: 'shortcut', type: 'string', description: 'Optional displayed command shortcut.' },
                    { name: 'disabled', type: 'boolean', description: 'Prevents navigation and selection.' },
                ],
            },
            { name: 'H0CommandVariant', fields: [{ name: 'H0CommandVariant', type: "'surface' | 'secondary' | 'ghost' | 'outline'", description: 'Built-in trigger appearances.' }] },
            { name: 'H0CommandBackdrop', fields: [{ name: 'H0CommandBackdrop', type: "'opaque' | 'blur' | 'transparent'", description: 'Shared modal backdrop appearances.' }] },
            { name: 'H0CommandSize', fields: [{ name: 'H0CommandSize', type: "'sm' | 'md' | 'lg'", description: 'Built-in trigger sizes.' }] },
            { name: 'H0CommandWindowSize', fields: [{ name: 'H0CommandWindowSize', type: "'sm' | 'md' | 'lg'", description: 'Command window sizes.' }] },
        ],
    },
    useWhen: ['Users need fast keyboard access to application actions or navigation.', 'A searchable grouped action list should open in a modal surface.'],
    avoidWhen: ['A standard select field represents form data.', 'Only one immediate button action is available.'],
    accessibility: ['Keep labels concise and provide a specific ariaLabel when needed.', 'Disabled items are skipped by Arrow, Home, End, and Enter navigation.', 'Preserve the built-in combobox/listbox relationship when customizing item content.'],
    styling: ['Use variant and size for the trigger, windowSize for the panel, and backdrop for the interaction layer.', 'Treat internal search and result selectors as implementation details.'],
    responsive: ['All window sizes retain viewport insets and a separately scrolling result region.'],
    performance: ['Filtering is synchronous; supply a reduced externally filtered collection for very large datasets.'],
    examples: [
        { key: 'components/command/BasicExample', purpose: 'Grouped commands, icons, selection, and a mod+k hotkey.' },
        { key: 'components/command/VariantsExample', purpose: 'Surface, secondary, ghost, and outline triggers.' },
        { key: 'components/command/TriggerSizesExample', purpose: 'Small, medium, and large trigger controls.' },
        { key: 'components/command/WindowSizesExample', purpose: 'Independent small, medium, and large command windows.' },
        { key: 'components/command/BackdropsExample', purpose: 'Opaque, blurred, and transparent overlay backdrops.' },
    ],
    relatedComponents: ['H0Modal', 'H0SearchField', 'H0List'],
} satisfies ComponentAgentRecordV1
