import type { ComponentAgentRecordV1 } from '../schema.ts'

export const dataTableAgentRecord = {
    schemaVersion: 1,
    component: 'H0DataTable',
    status: 'migrated',
    summary: 'Data-driven table with client or server state, filters, sorting, selection, pagination, infinite loading, and fixed-row virtualization.',
    imports: {
        components: ['H0DataTable'],
        types: [
            'H0DataTableColumn',
            'H0DataTableEmits',
            'H0DataTableFilter',
            'H0DataTableFilters',
            'H0DataTableFilterValue',
            'H0DataTableMode',
            'H0DataTablePaginationMode',
            'H0DataTableProps',
            'H0DataTableSelectFilter',
            'H0DataTableSelection',
            'H0DataTableSelectionMode',
            'H0DataTableSort',
            'H0DataTableSortDirection',
            'H0DataTableTextFilter',
        ],
        styles: ['@h0nio/ui/style.css'],
    },
    api: {
        props: [
            { name: 'columns', type: 'H0DataTableColumn<Row>[]', description: 'Table columns plus optional sorting and filtering behavior.' },
            { name: 'rows', type: 'Row[]', default: '[]', description: 'Complete client dataset or current server page/chunk.' },
            { name: 'getRowKey', type: '(row: Row, index: number) => H0TableRowKey', description: 'Required stable and unique row identity.' },
            { name: 'mode', type: 'H0DataTableMode', default: "'client'", description: 'Selects local transformation or externally managed data.' },
            { name: 'paginationMode', type: 'H0DataTablePaginationMode', default: "'none'", description: 'Selects no paging, page controls, or infinite load-more behavior.' },
            { name: 'page', type: 'number', default: 'undefined', description: 'Controlled one-based page.' },
            { name: 'defaultPage', type: 'number', default: '1', description: 'Initial uncontrolled page.' },
            { name: 'pageSize', type: 'number', default: 'undefined', description: 'Controlled items per page; no built-in page-size control is rendered.' },
            { name: 'defaultPageSize', type: 'number', default: '10', description: 'Initial uncontrolled items per page.' },
            { name: 'totalItems', type: 'number', default: '0', description: 'Complete server count used by page pagination; ignored by the client pipeline.' },
            { name: 'sort', type: 'H0DataTableSort', default: 'undefined', description: 'Controlled sort model.' },
            { name: 'defaultSort', type: 'H0DataTableSort', default: 'null', description: 'Initial uncontrolled sort.' },
            { name: 'filters', type: 'H0DataTableFilters', default: 'undefined', description: 'Controlled filter values by column key.' },
            { name: 'defaultFilters', type: 'H0DataTableFilters', default: '{}', description: 'Initial uncontrolled filters.' },
            { name: 'selection', type: 'H0DataTableSelection', default: 'undefined', description: 'Controlled selected row keys.' },
            { name: 'defaultSelection', type: 'H0DataTableSelection', default: '[]', description: 'Initial uncontrolled selected keys.' },
            { name: 'selectionMode', type: 'H0DataTableSelectionMode', default: "'none'", description: 'Disables selection or adds single or multiple key selection.' },
            { name: 'isRowSelectable', type: '(row: Row) => boolean', default: '() => true', description: 'Disables selection controls for chosen rows without suppressing row-click.' },
            { name: 'loading', type: 'boolean', default: 'false', description: 'Marks initial, server-page, or incremental infinite loading.' },
            { name: 'error', type: 'string', default: "''", description: 'Shows an empty error state or an alert above retained rows.' },
            { name: 'hasMore', type: 'boolean', default: 'false', description: 'Allows additional infinite load-more requests.' },
            { name: 'virtual', type: 'boolean', default: 'false', description: 'Enables fixed-row windowing outside page mode.' },
            { name: 'rowHeight', type: 'number', default: '48', description: 'Positive fixed virtual row height and infinite trigger unit in pixels.' },
            { name: 'overscan', type: 'number', default: '5', description: 'Virtual rows rendered before and after the visible window; negative values act as zero.' },
            { name: 'scrollHeight', type: 'string | number', default: 'undefined', description: 'Maximum table viewport height; required for virtualization and numbers become pixels.' },
            { name: 'minWidth', type: 'string | number', default: 'undefined', description: 'Minimum table width before horizontal scrolling; numbers become pixels.' },
            { name: 'density', type: 'H0TableDensity', default: "'default'", description: 'Cell spacing forwarded to H0Table.' },
            { name: 'striped', type: 'boolean', default: 'false', description: 'Alternates row surfaces.' },
            { name: 'hoverable', type: 'boolean', default: 'true', description: 'Highlights hovered rows without changing interaction.' },
            { name: 'bordered', type: 'boolean', default: 'true', description: 'Adds table border treatment.' },
            { name: 'stickyHeader', type: 'boolean', default: 'true', description: 'Keeps headers visible while scrolling.' },
            { name: 'emptyText', type: 'string', default: 'Localized empty text', description: 'A non-empty value overrides localized empty-state copy.' },
            { name: 'loadingText', type: 'string', default: 'Localized loading text', description: 'A non-empty value overrides localized loading-state copy.' },
            { name: 'ariaLabel', type: 'string', default: 'Localized data-table label', description: 'Accessible dataset name.' },
        ],
        events: [
            { name: 'update:sort', type: 'H0DataTableSort', description: 'Requests a controlled sort update; sorting also requests page 1.' },
            { name: 'update:filters', type: 'H0DataTableFilters', description: 'Requests a controlled filter update; filtering also requests page 1.' },
            { name: 'update:selection', type: 'H0DataTableSelection', description: 'Requests a controlled selected-key update.' },
            { name: 'update:page', type: 'number', description: 'Requests a controlled one-based page update.' },
            { name: 'update:pageSize', type: 'number', description: 'Declared page-size model event; no built-in interaction currently emits it.' },
            { name: 'load-more', type: '\u2014', description: 'Requests the next infinite chunk near the viewport end.' },
            { name: 'row-click', type: '[row: Row, index: number, event: MouseEvent]', description: 'Reports a clicked displayed row; index is page- or virtual-window-relative and is not identity.' },
        ],
        slots: [
            { name: 'toolbar', type: '{ filters: H0DataTableFilters | undefined; setFilter: (key: string, value: H0DataTableFilterValue) => void }', description: 'Controls above the table; filters reflects the controlled prop and can be undefined.' },
            { name: 'filter-[key]', type: '{ column: H0DataTableColumn<Row>; value: H0DataTableFilterValue; setFilter: (value: H0DataTableFilterValue) => void }', description: 'Custom filter control with resolved state for a column key.' },
            { name: 'cell-[key]', type: '{ row: Row; column: H0DataTableColumn<Row>; value: unknown; rowIndex: number }', description: 'Custom body-cell content for a column key.' },
            { name: 'empty', type: '\u2014', description: 'Replacement empty state when no error exists.' },
            { name: 'error', type: '{ error: string }', description: 'Replacement error state used only when no rows exist.' },
        ],
        exposed: [],
        types: [
            { name: 'H0DataTableMode', fields: [{ name: 'H0DataTableMode', type: "'client' | 'server'", description: 'Local transformation or externally prepared rows.' }] },
            { name: 'H0DataTablePaginationMode', fields: [{ name: 'H0DataTablePaginationMode', type: "'none' | 'page' | 'infinite'", description: 'Supported pagination and loading strategies.' }] },
            { name: 'H0DataTableSelectionMode', fields: [{ name: 'H0DataTableSelectionMode', type: "'none' | 'single' | 'multiple'", description: 'Supported row-key selection behaviors.' }] },
            { name: 'H0DataTableSortDirection', fields: [{ name: 'H0DataTableSortDirection', type: "'asc' | 'desc'", description: 'Supported sort directions.' }] },
            { name: 'H0DataTableSort', fields: [{ name: 'H0DataTableSort', type: '{ key: string; direction: H0DataTableSortDirection } | null', description: 'Active sort column and direction, or no sorting.' }] },
            { name: 'H0DataTableFilterValue', fields: [{ name: 'H0DataTableFilterValue', type: 'string | number | boolean | null', description: 'Supported filter model values.' }] },
            { name: 'H0DataTableFilters', fields: [{ name: 'H0DataTableFilters', type: 'Record<string, H0DataTableFilterValue>', description: 'Filter values indexed by column key.' }] },
            {
                name: 'H0DataTableTextFilter',
                fields: [
                    { name: 'type', type: "'text'", description: 'Selects the built-in text search field.' },
                    { name: 'placeholder', type: 'string', description: 'Optional search placeholder overriding localized copy.' },
                ],
            },
            {
                name: 'H0DataTableSelectFilter',
                fields: [
                    { name: 'type', type: "'select'", description: 'Selects the built-in select control.' },
                    { name: 'options', type: 'H0SelectOption[]', description: 'Public H0Select options.' },
                    { name: 'placeholder', type: 'string', description: 'Optional select placeholder overriding localized copy.' },
                ],
            },
            { name: 'H0DataTableFilter', fields: [{ name: 'H0DataTableFilter', type: 'H0DataTableTextFilter | H0DataTableSelectFilter', description: 'Built-in filter configuration union.' }] },
            { name: 'H0DataTableSelection', fields: [{ name: 'H0DataTableSelection', type: 'H0TableRowKey[]', description: 'Selected stable row keys.' }] },
            {
                name: 'H0DataTableColumn',
                description: 'H0TableColumn<Row> plus data transformation behavior.',
                fields: [
                    { name: 'sortable', type: 'boolean', description: 'Enables the built-in sort trigger.' },
                    { name: 'sortValue', type: '(row: Row) => unknown', description: 'Resolves the scalar sorting value before base column value.' },
                    { name: 'compare', type: '(left: Row, right: Row) => number', description: 'Custom comparison whose result is adjusted for direction.' },
                    { name: 'filter', type: 'H0DataTableFilter', description: 'Built-in text or select filter control.' },
                    { name: 'filterValue', type: '(row: Row) => unknown', description: 'Resolves the value used by built-in filtering before base column value.' },
                    { name: 'filterPredicate', type: '(row: Row, value: H0DataTableFilterValue) => boolean', description: 'Custom client filter predicate taking precedence over built-in matching.' },
                ],
            },
        ],
    },
    useWhen: ['A dataset needs built-in sorting, filtering, selection, pagination, infinite loading, or virtualization.', 'Client and server data flows should share one table interface.'],
    avoidWhen: ['A simple presentational table is enough; use H0Table.', 'Rows have variable height but virtualization is required.'],
    accessibility: ['Provide a specific ariaLabel.', 'Keep row keys unique and stable.', 'Preserve labeled filters, selection controls, alerts, and visible status text.', 'Do not treat row-click as a keyboard-accessible primary action.', 'Prefer pagination when virtualized windowing would hide required table context from assistive technology.'],
    styling: ['Use density, striped, hoverable, bordered, and stickyHeader before local overrides.', 'Use cell and toolbar slots with public tokens.', 'Treat sorting, selection, and virtualization selectors as implementation details.'],
    responsive: ['Use column minimum widths and minWidth for horizontal overflow.', 'Consider fewer columns or a summary layout on narrow screens.'],
    performance: ['Prefer server mode for remote or expensive datasets.', 'Use fixed-row virtualization for large local collections.', 'Tune overscan conservatively.', 'Keep columns, rows, key functions, and transformation callbacks stable.'],
    examples: [
        { key: 'components/data-table/ClientExample', purpose: 'Controlled client sorting, filtering, page selection, and pagination.' },
        { key: 'components/data-table/ServerExample', purpose: 'Externally managed page and sort state with simulated loading.' },
        { key: 'components/data-table/InfiniteLoadingExample', purpose: 'Locked incremental loading that appends chunks near the viewport end.' },
        { key: 'components/data-table/VirtualExample', purpose: 'Ten-thousand-row fixed-height virtualization with bounded DOM.' },
        { key: 'components/data-table/SlotsAndErrorsExample', purpose: 'Toolbar, custom filter and cell slots, disabled selection, and both error presentations.' },
    ],
    relatedComponents: ['H0Table', 'H0Pagination', 'H0InfiniteScroll', 'H0Select'],
} satisfies ComponentAgentRecordV1
