import type { ComponentAgentRecordV1 } from '../schema.ts'
import { focusBlurEvents, standardFormGuidance } from './forms-shared.ts'

export const selectAgentRecord = {
    schemaVersion: 1, component: 'H0Select', status: 'migrated', summary: 'Accessible single or multiple option picker with custom rendering, virtualization, loading state, and teleported listbox.',
    imports: { components: ['H0Select'], types: ['H0SelectEmits', 'H0SelectOption', 'H0SelectProps', 'H0SelectSize', 'H0SelectValue', 'H0SelectVariant'], styles: ['@h0nio/ui/style.css'] },
    api: { props: [
        { name: 'modelValue', type: 'H0SelectValue | H0SelectValue[] | null', default: 'undefined', description: 'Controlled selection.' }, { name: 'defaultValue', type: 'H0SelectValue | H0SelectValue[] | null', default: 'null', description: 'Initial selection.' }, { name: 'options', type: 'H0SelectOption[]', default: '[]', description: 'Available options.' },
        { name: 'multiple', type: 'boolean', default: 'false', description: 'Allows several values.' }, { name: 'maxSelected', type: 'number', default: 'undefined', description: 'Maximum selected values.' }, { name: 'size', type: 'H0SelectSize', default: "'md'", description: 'Control size.' }, { name: 'variant', type: 'H0SelectVariant', default: "'surface'", description: 'Trigger background treatment.' },
        { name: 'label', type: 'string', default: "''", description: 'Visible label.' }, { name: 'placeholder', type: 'string', default: 'Localized', description: 'Empty selection copy.' }, { name: 'disabled', type: 'boolean', default: 'false', description: 'Disables interaction.' }, { name: 'loading', type: 'boolean', default: 'false', description: 'Shows pending options.' }, { name: 'required', type: 'boolean', default: 'false', description: 'Requires a selection.' },
        { name: 'error', type: 'string', default: "''", description: 'Validation error.' }, { name: 'hint', type: 'string', default: "''", description: 'Supporting copy.' }, { name: 'id', type: 'string', default: "''", description: 'Control id.' }, { name: 'name', type: 'string', default: "''", description: 'Form field name.' },
        { name: 'emptyText', type: 'string', default: 'Localized', description: 'Empty list copy.' }, { name: 'closeOnSelect', type: 'boolean', default: '!multiple', description: 'Closes after choosing.' }, { name: 'listAriaLabel', type: 'string', default: 'Localized', description: 'Listbox accessible name.' },
        { name: 'virtual', type: 'boolean', default: 'false', description: 'Virtualizes option rows.' }, { name: 'optionHeight', type: 'number', default: '44', description: 'Virtual row height.' }, { name: 'overscan', type: 'number', default: '5', description: 'Extra virtual rows.' }, { name: 'scrollHeight', type: 'number | string', default: '320', description: 'Listbox maximum height.' },
        { name: 'teleportTo', type: 'string | HTMLElement', default: "'body'", description: 'Popup teleport target.' }, { name: 'teleportDisabled', type: 'boolean', default: 'false', description: 'Keeps popup local.' }, { name: 'rootAttrs', type: 'Record<string, unknown>', default: 'undefined', description: 'Attributes for the root.' }, { name: 'controlAttrs', type: 'Record<string, unknown>', default: 'undefined', description: 'Attributes for the trigger.' },
    ], events: [{ name: 'update:modelValue', type: 'H0SelectValue | H0SelectValue[] | null', description: 'Requests selection update.' }, { name: 'change', type: 'H0SelectValue | H0SelectValue[] | null', description: 'Reports committed selection.' }, { name: 'open', type: '—', description: 'Reports opening.' }, { name: 'close', type: '—', description: 'Reports closing.' }, ...focusBlurEvents], slots: [
        { name: 'label', type: '—', description: 'Custom label.' }, { name: 'value', type: '{ selectedOptions, value }', description: 'Custom selected-value display.' }, { name: 'option-start', type: '{ option, selected, index, visibleIndex }', description: 'Leading option content.' },
        { name: 'option', type: '{ option, selected, index, visibleIndex }', description: 'Custom option content.' }, { name: 'empty', type: '—', description: 'Custom empty state.' },
    ], exposed: [], types: [
        { name: 'H0SelectValue', fields: [{ name: 'H0SelectValue', type: 'string | number', description: 'Supported option and model value.' }] },
        { name: 'H0SelectSize', fields: [{ name: 'H0SelectSize', type: "'sm' | 'md' | 'lg'", description: 'Supported trigger sizes.' }] },
        { name: 'H0SelectVariant', fields: [{ name: 'H0SelectVariant', type: "'secondary' | 'surface'", description: 'Supported trigger surface treatments.' }] },
        { name: 'H0SelectOption', fields: [
            { name: 'label', type: 'string', description: 'Visible option label.' }, { name: 'value', type: 'Value', description: 'Option value preserving the generic Value type.' }, { name: 'description', type: 'string | undefined', description: 'Supporting copy.' }, { name: 'icon', type: 'H0IconDefinition | undefined', description: 'Optional icon.' }, { name: 'disabled', type: 'boolean | undefined', description: 'Disables selection.' },
        ] },
    ] },
    useWhen: ['Users choose from a known option list without free-text creation.'], avoidWhen: ['Free-text creation or remote filtering is central.'], ...standardFormGuidance,
    examples: [{ key: 'components/select/BasicExample', purpose: 'Single controlled option selection.' }, { key: 'components/select/MultipleExample', purpose: 'Multiple selection with a maximum.' }, { key: 'components/select/VariantsExample', purpose: 'Surface and secondary trigger treatments.' }, { key: 'components/select/SizesExample', purpose: 'Small, medium, and large trigger sizes.' }, { key: 'components/select/StatesExample', purpose: 'Loading, disabled, invalid, and empty states.' }, { key: 'components/select/VirtualExample', purpose: 'Virtualized fixed-height option list.' }], relatedComponents: ['H0RadioGroup', 'H0Form'],
} satisfies ComponentAgentRecordV1
