import type { ComponentAgentRecordV1 } from '../schema.ts'

export const tableAgentRecord = {
    schemaVersion: 1,
    component: 'H0Table',
    status: 'migrated',
    summary: 'Semantic presentational table with typed columns, custom cells, density variants, and managed scroll geometry.',
    imports: { components: ['H0Table'], types: ['H0TableAriaSort', 'H0TableColumn', 'H0TableColumnAlign', 'H0TableColumnSizing', 'H0TableDensity', 'H0TableEmits', 'H0TableGetRowKey', 'H0TableProps', 'H0TableRow', 'H0TableRowKey'], styles: ['@h0nio/ui/style.css'] },
    api: {
        props: [
            { name: 'columns', type: 'H0TableColumn<Row>[]', description: 'Column definitions in visible order.' },
            { name: 'rows', type: 'Row[]', default: '[]', description: 'Rows rendered in the table body.' },
            { name: 'getRowKey', type: 'H0TableGetRowKey<Row>', default: 'row index', description: 'Returns stable identity for each row.' },
            { name: 'columnSizing', type: 'H0TableColumnSizing', default: "'auto'", description: 'Uses intrinsic sizing or fixed layout with equal unconstrained columns.' },
            { name: 'density', type: 'H0TableDensity', default: "'default'", description: 'Controls cell padding.' },
            { name: 'striped', type: 'boolean', default: 'false', description: 'Alternates row surfaces.' },
            { name: 'hoverable', type: 'boolean', default: 'false', description: 'Adds pointer-hover row highlighting without changing interaction.' },
            { name: 'bordered', type: 'boolean', default: 'false', description: 'Adds an inset outer border.' },
            { name: 'stickyHeader', type: 'boolean', default: 'true', description: 'Keeps column headers visible while the viewport scrolls.' },
            { name: 'scrollHeight', type: 'string | number', default: 'undefined', description: 'Maximum internal viewport height; numbers become pixels.' },
            { name: 'minWidth', type: 'string | number', default: 'undefined', description: 'Minimum table width before horizontal scrolling; numbers become pixels.' },
            { name: 'loading', type: 'boolean', default: 'false', description: 'Shows the loading state only when no rows exist.' },
            { name: 'emptyText', type: 'string', default: 'Localized empty text', description: 'A non-empty value overrides localized empty-state copy.' },
            { name: 'loadingText', type: 'string', default: 'Localized loading text', description: 'A non-empty value overrides localized loading copy and label.' },
            { name: 'caption', type: 'string', default: "''", description: 'Visible native table caption.' },
            { name: 'ariaLabel', type: 'string', default: 'Localized table label', description: 'Accessible table name and basis for the scroll-area name.' },
        ],
        events: [
            { name: 'row-click', type: '[row: Row, index: number, event: MouseEvent]', description: 'Reports a clicked data row; descendant clicks bubble unless stopped.' },
            { name: 'viewport-scroll', type: 'Event', description: 'Reports the native internal viewport scroll event.' },
        ],
        slots: [
            { name: 'caption', type: '\u2014', description: 'Custom native table caption.' },
            { name: 'header-[key]', type: '{ column: H0TableColumn<Row> }', description: 'Custom header content for a column key.' },
            { name: 'cell-[key]', type: '{ row: Row; column: H0TableColumn<Row>; value: unknown; rowIndex: number }', description: 'Custom body cell content for a column key.' },
            { name: 'before-rows', type: '{ columnCount: number }', description: 'Valid table rows inserted inside tbody before data rows.' },
            { name: 'after-rows', type: '{ columnCount: number }', description: 'Valid table rows inserted inside tbody after data rows.' },
            { name: 'loading', type: '\u2014', description: 'Replacement content inside the component-owned loading cell.' },
            { name: 'empty', type: '\u2014', description: 'Replacement content inside the component-owned empty cell.' },
        ],
        exposed: [],
        types: [
            {
                name: 'H0TableColumn',
                description: 'Generic column definition for Row.',
                fields: [
                    { name: 'key', type: 'string', description: 'Row property and dynamic slot identifier.' },
                    { name: 'label', type: 'string', description: 'Visible fallback header label.' },
                    { name: 'width', type: 'string | number', description: 'Preferred CSS width; numbers become pixels.' },
                    { name: 'minWidth', type: 'string | number', description: 'Minimum CSS width; numbers become pixels.' },
                    { name: 'maxWidth', type: 'string | number', description: 'Maximum CSS width; numbers become pixels.' },
                    { name: 'align', type: 'H0TableColumnAlign', description: 'Body-cell alignment.' },
                    { name: 'headerAlign', type: 'H0TableColumnAlign', description: 'Header alignment falling back to align.' },
                    { name: 'ariaSort', type: 'H0TableAriaSort', description: 'Externally managed accessible sort state.' },
                    { name: 'value', type: '(row: Row) => unknown', description: 'Derived value rendered by default and passed to the cell slot.' },
                ],
            },
            { name: 'H0TableColumnAlign', fields: [{ name: 'H0TableColumnAlign', type: "'left' | 'center' | 'right'", description: 'Supported header and body-cell alignments.' }] },
            { name: 'H0TableColumnSizing', fields: [{ name: 'H0TableColumnSizing', type: "'auto' | 'equal'", description: 'Intrinsic or fixed equal-column table layout.' }] },
            { name: 'H0TableDensity', fields: [{ name: 'H0TableDensity', type: "'compact' | 'default' | 'comfortable'", description: 'Supported cell spacing densities; aliases H0Density.' }] },
            { name: 'H0TableAriaSort', fields: [{ name: 'H0TableAriaSort', type: "'ascending' | 'descending' | 'none'", description: 'Native aria-sort values supported by a column.' }] },
            { name: 'H0TableRow', fields: [{ name: 'H0TableRow', type: 'Record<string, unknown>', description: 'Base constraint for generic row objects.' }] },
            { name: 'H0TableRowKey', fields: [{ name: 'H0TableRowKey', type: 'string | number', description: 'Supported stable row identity.' }] },
            { name: 'H0TableGetRowKey', fields: [{ name: 'H0TableGetRowKey<Row>', type: '(row: Row, index: number) => H0TableRowKey', description: 'Generic stable-key resolver.' }] },
        ],
    },
    useWhen: ['Semantic tabular markup is required.', 'Sorting, filtering, and paging are handled by application logic.'],
    avoidWhen: ['Built-in data manipulation or selection is required; use H0DataTable.', 'The content is better understood as cards or a key-value list on every viewport.'],
    accessibility: ['Provide a specific ariaLabel and optional visible caption.', 'Use stable row keys and meaningful headers.', 'Set ariaSort from external state only for the active sorting column.', 'Do not treat row-click as a keyboard-accessible primary action; use interactive controls inside cells.'],
    styling: ['Use density, striped, hoverable, and bordered before local overrides.', 'Customize values through cell slots and public tokens.', 'Treat internal table selectors as implementation details.'],
    responsive: ['Use column minimum widths and minWidth to enable readable horizontal scrolling.', 'Avoid compressing dense columns beyond readability.'],
    performance: ['Keep columns, row arrays, and getRowKey stable.', 'Use H0DataTable virtualization for large fixed-height datasets.'],
    examples: [
        { key: 'components/table/BasicExample', purpose: 'Typed semantic table with a stable row key and custom status cell.' },
        { key: 'components/table/LayoutExample', purpose: 'Compact equal columns with horizontal and vertical scrolling plus a sticky header.' },
        { key: 'components/table/StatesExample', purpose: 'Localized and customized empty and loading states.' },
        { key: 'components/table/CustomContentExample', purpose: 'Derived values, dynamic header and cell slots, summary rows, and separated row and cell actions.' },
    ],
    relatedComponents: ['H0DataTable', 'H0Badge', 'H0Button', 'H0Link'],
} satisfies ComponentAgentRecordV1
