import type { ComponentAgentRecordV1 } from '../schema.ts'

export const toastAgentRecord = {
    schemaVersion: 1, component: 'H0Toast', status: 'migrated', summary: 'Visual transient notification with semantic tone, icon, content slots, localized close control, and polite status announcement.',
    imports: { components: ['H0Toast', 'H0Toasts', 'createH0ToastService', 'provideH0Toast', 'useH0Toast'], types: ['H0IconSource', 'H0ToastCloseMode', 'H0ToastConfig', 'H0ToastEmits', 'H0ToastId', 'H0ToastInput', 'H0ToastItem', 'H0ToastPlacement', 'H0ToastProps', 'H0ToastService', 'H0ToastState', 'H0ToastTone'], styles: ['@h0nio/ui/style.css'] },
    api: {
        props: [{ name: 'tone', type: 'H0ToastTone', default: "'default'", description: 'Semantic intent and default icon.' }, { name: 'title', type: 'string', default: "''", description: 'Primary notification text.' }, { name: 'description', type: 'string', default: "''", description: 'Preferred secondary text.' }, { name: 'text', type: 'string', default: "''", description: 'Compatibility alias used when description is absent.' }, { name: 'icon', type: 'H0IconSource', default: 'undefined', description: 'Legacy node or @h0nio/icons body definition overriding the tone icon.' }, { name: 'closable', type: 'boolean', default: 'true', description: 'Shows the localized close button.' }],
        events: [{ name: 'close', type: '—', description: 'Requests dismissal of the visual toast.' }], slots: [{ name: 'title', type: '—', description: 'Custom primary content.' }, { name: 'default', type: '—', description: 'Custom description content.' }], exposed: [],
        types: [
            { name: 'H0ToastTone', fields: [{ name: 'H0ToastTone', type: "'default' | 'info' | 'success' | 'warning' | 'danger'", description: 'Supported semantic notification tones.' }] },
            { name: 'H0ToastInput', fields: [{ name: 'title', type: 'string', default: 'undefined', description: 'Optional primary text.' }, { name: 'description', type: 'string', default: 'undefined', description: 'Optional secondary text.' }, { name: 'icon', type: 'H0IconSource', default: 'undefined', description: 'Optional legacy node or @h0nio/icons body definition.' }, { name: 'duration', type: 'number', default: 'Required', description: 'Lifetime in milliseconds; zero is persistent.' }, { name: 'tone', type: 'H0ToastTone', default: "'default'", description: 'Semantic intent.' }, { name: 'placement', type: 'H0ToastPlacement', default: 'Current service placement', description: 'Optional stack placement update.' }, { name: 'closeMode', type: 'H0ToastCloseMode', default: "'button'", description: 'Button or surface dismissal behavior.' }] },
            { name: 'H0ToastPlacement', fields: [{ name: 'H0ToastPlacement', type: "'top-start' | 'top' | 'top-end' | 'bottom-start' | 'bottom' | 'bottom-end'", description: 'Supported logical stack placements.' }] },
            { name: 'H0ToastCloseMode', fields: [{ name: 'button', type: "'button'", description: 'Shows the close button; the toast surface itself does not dismiss.' }, { name: 'toast', type: "'toast'", description: 'Shows the close button and also dismisses from a surface click.' }, { name: 'container', type: "'container'", description: 'Hides the close button and dismisses from a surface click.' }] },
            { name: 'H0ToastConfig', fields: [{ name: 'placement', type: 'H0ToastPlacement', default: "'bottom-end'", description: 'Initial or configured stack placement.' }] },
            { name: 'H0ToastId', fields: [{ name: 'H0ToastId', type: 'string', description: 'Opaque identifier returned by show and tone helpers.' }] },
            { name: 'H0ToastItem', description: 'Normalized service-owned toast entry.', fields: [{ name: 'id', type: 'H0ToastId', description: 'Generated stable identifier.' }, { name: 'createdAt', type: 'number', description: 'Creation timestamp in milliseconds.' }, { name: 'duration', type: 'number', description: 'Configured lifetime in milliseconds.' }, { name: 'tone', type: 'H0ToastTone', description: 'Resolved semantic tone.' }, { name: 'closeMode', type: 'H0ToastCloseMode', description: 'Resolved dismissal behavior.' }, { name: 'title / description / icon / placement', type: 'H0ToastInput fields', description: 'Optional input values retained by the service.' }] },
            { name: 'H0ToastState', fields: [{ name: 'toasts', type: 'H0ToastItem[]', description: 'Reactive service-owned notification list.' }, { name: 'placement', type: 'H0ToastPlacement', description: 'Current stack placement.' }] },
            { name: 'H0ToastService', fields: [{ name: 'show', type: '(input: H0ToastInput) => H0ToastId', description: 'Creates a toast.' }, { name: 'default / info / success / warning / danger', type: '(input: Omit<H0ToastInput, \'tone\'>) => H0ToastId', description: 'Creates a toast with a predefined tone.' }, { name: 'update', type: '(id, input: Partial<H0ToastInput>) => void', description: 'Updates content, behavior, placement, or duration.' }, { name: 'configure', type: '(config: H0ToastConfig) => void', description: 'Changes service placement.' }, { name: 'dismiss', type: '(id: H0ToastId) => void', description: 'Dismisses one toast.' }, { name: 'dismissAll', type: '() => void', description: 'Dismisses every toast.' }, { name: 'dispose', type: '() => void', description: 'Clears timers and toasts.' }] },
        ],
    },
    useWhen: ['Transient global feedback should not interrupt the task.', 'An operation changes state and needs brief confirmation.'], avoidWhen: ['Feedback must remain next to its source; use H0Alert.', 'A user decision is required; use a dialog.', 'Critical failure details must remain available.'], accessibility: ['Keep messages concise.', 'Use persistent duration cautiously and preserve dismissal.', 'Pair tone and icon with explicit text.', 'Update an existing toast instead of rapidly announcing progress as separate items.'], styling: ['Use tone and public tokens.', 'Treat toast layout selectors as implementation details.'], responsive: ['Toast width remains within the viewport and content wraps.'], performance: ['Use one H0Toasts per service.', 'Dismiss obsolete notifications and dispose manual services.'], examples: [
        { key: 'components/toast/StaticExample', purpose: 'All standalone visual tones.' },
        { key: 'components/toast/ContentExample', purpose: 'Custom icon, title slot, default slot, and closable state.' },
        { key: 'components/toast/ServiceExample', purpose: 'Manual service, update flow, and teleported stack.' },
        { key: 'components/toast/CloseModesExample', purpose: 'Button, toast, and container dismissal modes.' },
        { key: 'components/toast/PlacementExample', purpose: 'All service-level stack placements.' },
    ], relatedComponents: ['H0Toasts', 'H0Alert', 'H0Button'],
} satisfies ComponentAgentRecordV1
